services:
  db:
    image: docker.io/postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - 8080:8080
  backend:
    build: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8500:8500"
  frontend:
    build: frontend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
  fileserver:
    image: golang:1.23-alpine
    working_dir: /srv
    ports:
      - "5555:5555"
    volumes:
      - "./backend/test/file_server.go:/srv/file_server.go"
      - "./sample:/srv/sample"
    command: ["go", "run", "file_server.go"]
